version: "3.9"

services:
  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: auth_db
    networks:
      - app_network
    ports:
      - "5432:5432"

  course_db:
    image: postgres:15
    container_name: course_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: course_db
    networks:
      - app_network
    ports:
      - "5433:5432"

  user_db:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: user_db
    networks:
      - app_network
    ports:
      - "5434:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7056:7056"
    environment:
      - AUTH_DATABASE_URL=postgresql://root:root123@auth_db:5432/auth_db?schema=public
      - COURSE_DATABASE_URL=postgresql://root:root123@course_db:5432/course_db?schema=public
      - USER_DATABASE_URL=postgresql://root:root123@user_db:5432/user_db?schema=public
      - PORT=${PORT}
      - HOST=${HOST}
      - MODE=${MODE}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CODE_SEED=${CODE_SEED}
    networks:
      - app_network
    depends_on:
      - auth_db
      - course_db
      - user_db

networks:
  app_network:
    driver: bridge
